training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact

  # first we have to provide our pipeline name . Second parameter is each and every component will generate some artifact , so we have to store those artifact location at artifact_dir .

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 


# The above information we needed in data_ingestion_config .

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

# similarly for other configuration also .

data_transformation_config:
  add_bedroom_per_room: true
  # add_bedroom_per_room means adding addition column . If i want this column i will keep it's value = true and it i don't want this column i will keep it's value = false .Adding addition column basically means we are adding addition feattue .
  transformed_dir: transformed_data
  # Suppose i applied feature engineering on our dataset then our dataset will change . So, we will store that changed dataset in tranformed_data .
  transformed_train_dir: train
  # This transformed_data will contain train and test dataset . So, it means basicallly that we will have transformed_data folder which will contain train and test folder then train folder will contain new training set data .
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  # This preprocessed is the folder where i will store my pickle file .
  preprocessed_object_file_name: preprocessed.pkl
  # we will try to generate pickle file from our data transformation step . This preprocessed.pkl is our pickle file name .
  

model_trainer_config:
  # once we have trained our model ,we need to save it somewhtere and we will save it in trained_model_dir directory .
  trained_model_dir: trained_model
  # We have to specify model file name . The name of the file is model.pkl . After training the model , we wlll save that model in model.pkl file .
  model_file_name: model.pkl
  # whenever we train our model , we accept that 60% of accuracy should be there . R-square score should match with 0.6  . If it is less than that then we will not accept the model .
  base_accuracy: 0.6

  # Next we will have config folder which will contain model.yaml file and it will provide configuration about our model . Configuration like which paramete we want to try and which model we want to train .
  model_config_dir: config
  model_config_file_name: model.yaml


model_evaluation_config:
  # model_evaluation.yaml will give us the location the best model which is available in the production .
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models