# Schema file define structure for our dataset .
columns:
   longitude : float
   latitude : float
   housing_median_age : float
   total_rooms : float
   total_bedrooms : float
   population : float
   households : float
   median_income : float
   median_house_value : float
   ocean_proximity : category

numerical_columns:
 - longitude
 - latitude
 - housing_median_age
 - total_rooms
 - total_bedrooms
 - population
 - households
 - median_income

categorical_columns:
 - ocean_proximity 


target_column : median_house_value

domain_value:
  ocean_proximity:
     =  <1H OCEAN
     =  <INLAND
     =  <ISLAND
     =  <NEAR BAY
     =  <NEAR OCEAN

# Schema file has all columns name along with their datatypes . Basically Schema is like a structure which tells about how many columns we have , what is their data types , what is our target_column , what is our domain value .

# ocean_proximity is the category means what are the catrgories available inside ocean_proximity .

# target_column is basically our prediction column .
# for any column , we can check their unique values then we can define their domain values .

# category is also a kind of object .
# domain value is like what are the different value that are acceptable inside this ocean_proximity column . So, if we get some other category which we have not used here in domain then our model is going to fail .